//
//  ObserverID.h
//  StockFrame
//
//  Created by fdt on 2018/7/19.
//  Copyright © 2018年 ljt. All rights reserved.
//

#ifndef ObserverID_h
#define ObserverID_h

typedef NS_ENUM(NSUInteger, ObserverOption)
{
    OBSERVER_NETWORK_STATUS = 1,
    OBSERVER_UPDATE_CLOSED_POSITION = 2,
    OBSERVER_UPDATE_HIS_MATCH_LIST_DYNAMIC = 3,
    OBSERVER_UPDATE_TICK = 4,
    OBSERVER_UPDATE_GROUPS = 6,
    OBSERVER_UPDATE_QUOTE = 10,
    OBSERVER_UPDATE_ACCOUNT = 11,
    OBSERVER_UPDATE_ORDER = 12,
    OBSERVER_UPDATE_UNREACHED_ALERT = 13,
    OBSERVER_UPDATE_PUSH_NOTIFICATION = 14,
    OBSERVER_UPDATE_TRADE = 15,
    
    OBSERVER_UPDATE_PROFIT_RELOAD = 16,
    OBSERVER_UPDATE_PROFIT = 17,
    OBSERVER_UPDATE_PROFIT_FIRST = 18,
    OBSERVER_UPDATE_FORGOT_PWD = 19,
    OBSERVER_UPDATE_SYMBOL_SEARCH = 20,
    OBSERVER_UPDATE_SYMBOL_LIST = 21,
    OBSERVER_UPDATE_SYMBOL_NAME = 22,
    OBSERVER_UPDATE_TRADE_ALERT = 23,
    OBSERVER_UPDATE_PRICE_ALERT = 24,
    OBSERVER_UPDATE_PRICE_ALERT_SETTING = 25,
    OBSERVER_ACTION_PRICE_ALERT_SETTING_ERR = 26,
    OBSERVER_ACTION_RESET_ACCOUNT = 27,
    OBSERVER_UPDATE_ORDER_PENDING = 28,
    OBSERVER_UPDATE_ORDER_MARKET_CLOSE = 29,
    OBSERVER_UPDATE_CALCULATE_ORDER = 30,
    
    OBSERVER_UPDATE_LIVE_ACCOUNT_STATE = 32,
    OBSERVER_UPDATE_ACCOUNT_SETTING = 33,
    OBSERVER_UPDATE_PHONE_USAGE = 34,
    OBSERVER_UPDATE_USE_COIN = 35,
    OBSERVER_UPDATE_PORTFOLIO_GROUP_NAME = 36,
    OBSERVER_UPDATE_DEFAULT_QUANTITY = 37,
    OBSERVER_UPDATE_MAX_ORDER_QTY_ALLOW = 38,
    OBSERVER_UPDATE_GLOBAL_SETTING = 39,
    
    // IAP
    OBSERVER_UPDATE_IAP_PRODUCT_LIST = 40,
    OBSERVER_ACTION_IAP_PURCHASE = 41,
    OBSERVER_UPDATE_IAP_ERROR = 42,
    
    // PayPal
    OBSERVER_ACTION_PAYPAL_PURCHASE_STARTING = 43,
    OBSERVER_ACTION_PAYPAL_PURCHASE_DONE = 44,
    
    // Social
    OBSERVER_ACTION_SOCIAL_POST_DONE = 50,
    OBSERVER_ACTION_SOCIAL_POST_PROGRESS = 51,
    OBSERVER_ACTION_SOCIAL_COMMENT_DONE = 52,
    OBSERVER_ACTION_SOCIAL_COMMENT_LIKE_DONE = 53,
    OBSERVER_ACTION_SOCIAL_DELETE_COMMENT_DONE = 54,
    OBSERVER_UPDATE_SOCIAL_POST_LIST = 55,
    OBSERVER_UPDATE_SOCIAL_POST_DETAIL = 56,
    OBSERVER_UPDATE_SOCIAL_OTHERUSER_POST_LIST = 57,
    OBSERVER_UPDATE_SOCIAL_SEARCH_POST_LIST = 58,
    OBSERVER_UPDATE_SOCIAL_COMMENT_LIKE_USER = 59,
    OBSERVER_UPDATE_SET_SCHOOL_STATUS = 60,
    OBSERVER_ACTION_SEND_MAIL_DONE = 61,
    
    
    // Login
    
    OBSERVER_ACTION_3RD_USER_MAPPING = 80,
    OBSERVER_ACTION_3RD_USER_MAPPING_DETACH = 81,
    OBSERVER_ACTION_3RD_USER_MAPPING_LIST = 82,
    OBSERVER_ACTION_FB_LOGIN_ERROR = 83,
    OBSERVER_ACTION_WECHAT_LOGIN_ERROR = 84,
    OBSERVER_ACTION_QQ_LOGIN_ERROR = 85,
    
    OBSERVER_ACTION_LOGIN = 86,
    OBSERVER_ACTION_LOGOUT = 87,
    OBSERVER_ACTION_LOGIN_FAIL = 88,
    OBSERVER_ACTION_NEED_CHANGE_PASSWORD = 89,
    OBSERVER_ACTION_CHANGE_PASSWORD = 90,
    OBSERVER_ACTION_NEED_VERIFY_PHONE = 91,
    
    OBSERVER_UPDATE_SWITCH_MARKET = 100,
    OBSERVER_UPDATE_MARKET_LIST_CHANGE = 101,
    OBSERVER_UPDATE_FAVORITE_SYMBOL = 102,
    
    // Server status
    OBSERVER_ACTION_SERVER_STATUS_UPDATE = 110,
    
    
    // 財富管家分類行情 (200 ~ 300)
    OBSERVER_UPDATE_QUOTE_AND_RANK = 200,
    OBSERVER_UPDATE_LIGHT_WEIGHT_RANK = 201,
    
    /**
     *  Token update
     */
    OBSERVER_TOKEN_UPDATE = 301,
    
    /**
     *  <#Description#>
     */
    OBSERVER_WMJSON_UPDATE = 302,
    
    /**
     *  Symbol look up 結果update
     */
    OBSERVER_UPDATE_SYMBOL_LOOKUP = 303,
    /**
     *  历史
     */
    OBSERVER_WMHistoryTrade_UPDATE = 304,
    /**
     *  历史
     */
    OBSERVER_WMHistoryOrder_UPDATE = 305,
    
    /**
     *  手机验证码登录
     */
    OBSERVER_WMSmsLogin= 306,
    
    
    OBSERVER_DEBUG = 99999,
    
};

#endif /* ObserverID_h */
